# Name and version
name: Slimefun
version: ${project.version}

# Project metadata
author: The Slimefun 4 Community
website: https://github.com/Slimefun
description: Slimefun 无需安装任何模组即可将你的整个服务器变成一个 FTB 模组包

# Technical settings
main: io.github.thebusybiscuit.slimefun4.implementation.Slimefun
api-version: '1.16'

# (Soft) dependencies of Slimefun, we hook into these plugins.
softdepend:
- PlaceholderAPI
- WorldEdit
- ClearLag
- mcMMO
- ItemsAdder
- Orebfuscator

# Our commands
commands:
  slimefun:
    aliases: sf
    description: Slimefun 基础命令
    usage: 你安装的 Slimefun 版本似乎与服务器环境不兼容。请查看控制台获取详细信息。

# Default permissions
permissions:
  slimefun.command.guide:
    description: 允许你获取 Slimefun 指南书
    default: true
  slimefun.command.search:
    description: 允许你使用 /sf search
    default: true
  slimefun.command.open_guide:
    description: 允许你无需指南书直接打开 Slimefun 指南
    default: op
  slimefun.cheat.items:
    description: 允许你作弊获取物品
    default: op
  slimefun.cheat.researches:
    description: 允许你作弊解锁研究
    default: op
  slimefun.stats.others:
    description: 允许你查看其他玩家的统计数据
    default: op
  slimefun.android.upload-script:
    description: 允许你上传机器人脚本
    default: op
  slimefun.command.timings:
    description: 允许你使用 /sf timings
    default: op
  slimefun.command.teleporter:
    description: 允许你使用 /sf teleporter
    default: op
  slimefun.command.versions:
    description: 允许你使用 /sf versions
    default: op
  slimefun.command.backpack:
    description: 允许你使用 /sf backpack
    default: op
  slimefun.command.charge:
    description: 允许你使用 /sf charge
    default: op
  slimefun.command.debug:
    description: 允许你使用 /sf debug
    default: op
  slimefun.android.bypass:
    description: 允许你编辑其他玩家的机器人
    default: op
  slimefun.cargo.bypass:
    description: Allows you to edit other Players Cargo Blocks
    default: op
  slimefun.inventory.bypass:
    description: Allows you to open all Slimefun Machines
    default: op
  slimefun.gps.bypass:
    description: Allows you to open all GPS inventories
    default: op
  slimefun.debugging:
    description: Allows you to use the debugging tool from Slimefun
    default: op
